version: 2
run:
  timeout: 5m
  tests: true
linters:
  enable:
    - staticcheck
    - govet
    - errcheck
    - ineffassign
    - unused
    - revive
    - gocritic
issues:
  exclude-use-default: false
